import { Arme } from './arme';

export const ArmeExotiqueCollection: Arme[] = [
    {
        id: '1',
        categorie: 'arme de corps à corps légère',
        nom: 'Dague brise-épée',
        prix: '10 po',
        degats: '1d4',
        critique: '20/x2',
        portee: '',
        poids: '1,5kg',
        special: 'Désarmement',
    },
    {
        id: '2',
        categorie: 'arme de corps à corps légère',
        nom: 'Kama',
        prix: '2 po',
        degats: '1d6',
        critique: '20/x2',
        portee: '',
        poids: '1kg',
        special: 'Croc-en-jambe',
    },
    {
        id: '3',
        categorie: 'arme de corps à corps légère',
        nom: 'Nunchaku',
        prix: '2 po',
        degats: '1d6',
        critique: '20/x2',
        portee: '',
        poids: '1kg',
        special: 'Désarmement',
    },
    {
        id: '4',
        categorie: 'arme de corps à corps légère',
        nom: 'Sai',
        prix: '1 po',
        degats: '1d4',
        critique: '20/x2',
        portee: '',
        poids: '500g',
        special: 'Désarmement',
    },
    {
        id: '5',
        categorie: 'arme de corps à corps légère',
        nom: 'Siangham',
        prix: '3 po',
        degats: '1d6',
        critique: '20/x2',
        portee: '',
        poids: '500g',
        special: '',
    },
    {
        id: '6',
        categorie: 'arme de corps à corps à une main',
        nom: 'Epée bâtarde',
        prix: '35 po',
        degats: '1d10',
        critique: '19-20/x2',
        portee: '',
        poids: '3kg',
        special: '',
    },
    {
        id: '7',
        categorie: 'arme de corps à corps à une main',
        nom: 'Epée de duel',
        prix: '20 po',
        degats: '1d8',
        critique: '19-20/x2',
        portee: '',
        poids: '1,5kg',
        special: '',
    },
    {
        id: '8',
        categorie: 'arme de corps à corps à une main',
        nom: 'Epée du temple',
        prix: '30 po',
        degats: '1d8',
        critique: '19-20/x2',
        portee: '',
        poids: '1,5kg',
        special: 'Croc-en-jambe',
    },
    {
        id: '9',
        categorie: 'arme de corps à corps à une main',
        nom: 'Facalta',
        prix: '18 po',
        degats: '1d8',
        critique: '19-20/x3',
        portee: '',
        poids: '2kg',
        special: '',
    },
    {
        id: '10',
        categorie: 'arme de corps à corps à une main',
        nom: 'Fouet',
        prix: '1 po',
        degats: '1d3',
        critique: '20/x2',
        portee: '',
        poids: '1kg',
        special: 'Allonge, Croc-en-jambe, Désarmement, Dégâts Non-létaux',
    },
    {
        id: '11',
        categorie: 'arme de corps à corps à une main',
        nom: 'hache de guerre Naine',
        prix: '30 po',
        degats: '1d10',
        critique: '20/x3',
        portee: '',
        poids: '4kg',
        special: '',
    },
    {
        id: '12',
        categorie: 'arme de corps à corps à une main',
        nom: 'Khophesh',
        prix: '20 po',
        degats: '1d8',
        critique: '19-20/x2',
        portee: '',
        poids: '4kg',
        special: 'Croc-en-jambe',
    },
    {
        id: '13',
        categorie: 'arme de corps à corps à une main',
        nom: 'Sabre dentelé',
        prix: '35 po',
        degats: '1d8',
        critique: '19-20/x2',
        portee: '',
        poids: '1kg',
        special: '',
    },
    {
        id: '14',
        categorie: 'arme de corps à corps à deux mains',
        nom: 'Chaîne cloutée',
        prix: '25 po',
        degats: '2d4',
        critique: '20/x2',
        portee: '',
        poids: '5kg',
        special: 'Croc-en-jambe, Désarmement',
    },
    {
        id: '15',
        categorie: 'arme de corps à corps à deux mains',
        nom: 'Double-Lame',
        prix: '100 po',
        degats: '1d8/1d8',
        critique: '19-20/x2',
        portee: '',
        poids: '5kg',
        special: 'Double',
    },
    {
        id: '16',
        categorie: 'arme de corps à corps à deux mains',
        nom: 'Epée tranchante',
        prix: '12 po',
        degats: '1d6',
        critique: '20/x2',
        portee: '',
        poids: '1kg',
        special: 'Croc-en-jambe, Désarmement',
    },
    {
        id: '17',
        categorie: 'arme de corps à corps à deux mains',
        nom: 'Fléau double',
        prix: '90 po',
        degats: '1d8/1d8',
        critique: '20/x2',
        portee: '',
        poids: '5kg',
        special: 'Croc-en-jambe, Désarmement, Double',
    },
    {
        id: '18',
        categorie: 'arme de corps à corps à deux mains',
        nom: 'Hache double Orque',
        prix: '60 po',
        degats: '1d8/1d8',
        critique: '20/x3',
        portee: '',
        poids: '7,5kg',
        special: 'Double',
    },
    {
        id: '19',
        categorie: 'arme de corps à corps à deux mains',
        nom: 'Happe-Vilain',
        prix: '15 po',
        degats: '1d2',
        critique: '18-20/x2',
        portee: '',
        poids: '5kg',
        special: 'Allonge',
    },
    {
        id: '20',
        categorie: 'arme de corps à corps à deux mains',
        nom: 'Lame elfique incurvée',
        prix: '80 po',
        degats: '1d10',
        critique: '18-20/x2',
        portee: '',
        poids: '3,5kg',
        special: 'Background nécessaire',
    },
    {
        id: '21',
        categorie: 'arme de corps à corps à deux mains',
        nom: 'Lance à chaîne',
        prix: '15 po',
        degats: '1d6/1d6',
        critique: '20/x2',
        portee: '',
        poids: '6,5kg',
        special: 'Croc-en-jambe',
    },
    {
        id: '22',
        categorie: 'arme de corps à corps à deux mains',
        nom: 'Marteau-piolet Gnome',
        prix: '20 po',
        degats: '1d8/1d6',
        critique: '20/x3-20/x4',
        portee: '',
        poids: '3kg',
        special: 'Croc-en-jambe, Double',
    },
    {
        id: '23',
        categorie: 'arme de corps à corps à deux mains',
        nom: 'Ugrosh Nain',
        prix: '50 po',
        degats: '1d8/1d6',
        critique: '20/x3',
        portee: '',
        poids: '6kg',
        special: 'Double, Réception',
    },
    {
        id: '24',
        categorie: 'arme à distance',
        nom: 'Arbalète de poing',
        prix: '100 po',
        degats: '1d4',
        critique: '19-20/x2',
        portee: '9m',
        poids: '1kg',
        special: '',
    },
    {
        id: '25',
        categorie: 'arme à distance',
        nom: 'Arbalète double',
        prix: '300 po',
        degats: '1d8',
        critique: '19-20/x2',
        portee: '24m',
        poids: '9kg',
        special: '',
    },
    {
        id: '26',
        categorie: 'arme à distance',
        nom: 'Arbalète légère à répétition',
        prix: '250 po',
        degats: '1d8',
        critique: '19-20/x2',
        portee: '24m',
        poids: '3kg',
        special: '',
    },
    {
        id: '27',
        categorie: 'arme à distance',
        nom: 'Arbalète lourde à répétition',
        prix: '400 po',
        degats: '1d10',
        critique: '19-20/x2',
        portee: '36m',
        poids: '6kg',
        special: '',
    },
    {
        id: '28',
        categorie: 'arme à distance',
        nom: 'Bâton de jet Halfelin',
        prix: '20 po',
        degats: '1d8',
        critique: '20/x3',
        portee: '24m',
        poids: '1,5kg',
        special: '',
    },
    {
        id: '29',
        categorie: 'arme à distance',
        nom: 'Bolas',
        prix: '5 po',
        degats: '1d4',
        critique: '20/x2',
        portee: '3m',
        poids: '1kg',
        special: 'Croc-en-jambe, Dégâts Non-Létaux',
    },
    {
        id: '30',
        categorie: 'arme à distance',
        nom: 'Bolas Tribaux',
        prix: '15 po',
        degats: '1d4',
        critique: '20/x2',
        portee: '3m',
        poids: '1kg',
        special: 'Croc-en-jambe',
    },
    {
        id: '31',
        categorie: 'arme à distance',
        nom: 'Boomerang',
        prix: '3 po',
        degats: '1d6',
        critique: '20/x2',
        portee: '9m',
        poids: '1,5kg',
        special: 'Croc-en-jambe, Dégâts Non-Létaux',
    },
    {
        id: '32',
        categorie: 'arme à distance',
        nom: 'Filet',
        prix: '20 po',
        degats: '0',
        critique: '0',
        portee: '3m',
        poids: '3kg',
        special: 'Enchevêtrée',
    },
    {
        id: '33',
        categorie: 'arme à distance',
        nom: 'Lasso',
        prix: '1 pa',
        degats: '0',
        critique: '0',
        portee: '',
        poids: '2,5kg',
        special: 'Enchevêtrée',
    },
    {
        id: '34',
        categorie: 'arme à distance',
        nom: 'Shuriken(5)',
        prix: '1 po',
        degats: '1d2',
        critique: '20/x2',
        portee: '3m',
        poids: '250g',
        special: '',
    }
    ];
