import { Arme } from './arme';

export const ArmeGuerreCollection: Arme[] = [
    {
        id: '1',
        categorie: 'arme de corps à corps légère',
        nom: 'Armure à pointes',
        prix: 'à déterminer',
        degats: '1d6',
        critique: '20/x2',
        portee: '',
        poids: 'à déterminer',
        special: '',
    },
    {
        id: '2',
        categorie: 'arme de corps à corps légère',
        nom: 'Epée courte',
        prix: '10 po',
        degats: '1d6',
        critique: '19-20/x2',
        portee: '',
        poids: '1kg',
        special: '',
    },
    {
        id: '3',
        categorie: 'arme de corps à corps légère',
        nom: 'Hache de lancer',
        prix: '8 po',
        degats: '1d6',
        critique: '20/x2',
        portee: '3m',
        poids: '1kg',
        special: '',
    },
    {
        id: '4',
        categorie: 'arme de corps à corps légère',
        nom: 'hachette',
        prix: '6 po',
        degats: '1d6',
        critique: '20/x3',
        portee: '',
        poids: '1,5kg',
        special: '',
    },
    {
        id: '5',
        categorie: 'arme de corps à corps légère',
        nom: 'Kukri',
        prix: '8 po',
        degats: '1d4',
        critique: '18-20/x2',
        portee: '',
        poids: '1kg',
        special: '',
    },
    {
        id: '6',
        categorie: 'arme de corps à corps légère',
        nom: 'Lamétoile',
        prix: '24 po',
        degats: '1d4',
        critique: '20/x3',
        portee: '6m',
        poids: '1,5kg',
        special: '',
    },
    {
        id: '7',
        categorie: 'arme de corps à corps légère',
        nom: 'Matraque',
        prix: '1 po',
        degats: '1d6',
        critique: '20/x2',
        portee: '',
        poids: '1kg',
        special: 'dégâts non létaux',
    },
    {
        id: '8',
        categorie: 'arme de corps à corps légère',
        nom: 'Marteau léger',
        prix: '1 po',
        degats: '1d4',
        critique: '20/x2',
        portee: '6m',
        poids: '2kg',
        special: '',
    },
    {
        id: '9',
        categorie: 'arme de corps à corps légère',
        nom: 'Pic de guerre léger',
        prix: '4 po',
        degats: '1d4',
        critique: '20/x4',
        portee: '',
        poids: '1,5kg',
        special: '',
    },
    {
        id: '10',
        categorie: 'arme de corps à corps légère',
        nom: 'Rondache',
        prix: 'à déterminer',
        degats: '1d3',
        critique: '20/x2',
        portee: '',
        poids: 'à déterminer',
        special: '',
    },
    {
        id: '11',
        categorie: 'arme de corps à corps légère',
        nom: 'Rondache à pointes',
        prix: 'à déterminer',
        degats: '1d4',
        critique: '20/x2',
        portee: '',
        poids: 'à déterminer',
        special: '',
    },
    {
        id: '12',
        categorie: 'arme de corps à une main',
        nom: 'Canne épée',
        prix: '45 po',
        degats: '1d6',
        critique: '20/x2',
        portee: '',
        poids: '2kg',
        special: '',
    },
    {
        id: '13',
        categorie: 'arme de corps à une main',
        nom: 'Cimeterre',
        prix: '15 po',
        degats: '1d6',
        critique: '18-20/x2',
        portee: '',
        poids: '2kg',
        special: '',
    },
    {
        id: '14',
        categorie: 'arme de corps à une main',
        nom: 'Ecu',
        prix: 'à déterminer',
        degats: '1d4',
        critique: '20/x2',
        portee: '',
        poids: '2kg',
        special: '',
    },
    {
        id: '15',
        categorie: 'arme de corps à une main',
        nom: 'Ecu à pointe',
        prix: 'à déterminer',
        degats: '1d6',
        critique: '20/x2',
        portee: '',
        poids: '2kg',
        special: '',
    },
    {
        id: '16',
        categorie: 'arme de corps à une main',
        nom: 'Epée longue',
        prix: '15 po',
        degats: '1d8',
        critique: '19-20/x2',
        portee: '',
        poids: '2kg',
        special: '',
    },
    {
        id: '17',
        categorie: 'arme de corps à une main',
        nom: 'Fléau d\'armes léger',
        prix: '8 po',
        degats: '1d8',
        critique: '20/x2',
        portee: '',
        poids: '2,5kg',
        special: 'Croc-en-jambe, désarmement',
    },
    {
        id: '18',
        categorie: 'arme de corps à une main',
        nom: 'Hache d\'armes ',
        prix: '10 po',
        degats: '1d8',
        critique: '20/x3',
        portee: '',
        poids: '3kg',
        special: '',
    },
    {
        id: '19',
        categorie: 'arme de corps à une main',
        nom: 'Marteau de guerre',
        prix: '12 po',
        degats: '1d8',
        critique: '20/x3',
        portee: '',
        poids: '2,5kg',
        special: '',
    },
    {
        id: '20',
        categorie: 'arme de corps à une main',
        nom: 'Pic de guerre lourd',
        prix: '8 po',
        degats: '1d6',
        critique: '20/x4',
        portee: '',
        poids: '3kg',
        special: '',
    },
    {
        id: '21',
        categorie: 'arme de corps à une main',
        nom: 'Rapière ',
        prix: '20 po',
        degats: '1d6',
        critique: '18-20/x2',
        portee: '',
        poids: '1kg',
        special: '',
    },
    {
        id: '22',
        categorie: 'arme de corps à une main',
        nom: 'Trident ',
        prix: '15 po',
        degats: '1d8',
        critique: '20/x2',
        portee: '3m',
        poids: '2kg',
        special: '',
    },
    {
        id: '23',
        categorie: 'arme de corps à deux mains',
        nom: 'Bardiche ',
        prix: '13 po',
        degats: '1d10',
        critique: '19-20/x2',
        portee: '',
        poids: '7kg',
        special: 'Allonge, Réception',
    },
    {
        id: '24',
        categorie: 'arme de corps à deux mains',
        nom: 'Bac de corbin ',
        prix: '15 po',
        degats: '1d10',
        critique: '20/x3',
        portee: '',
        poids: '6kg',
        special: 'Allonge, Réception',
    },
    {
        id: '25',
        categorie: 'arme de corps à deux mains',
        nom: 'Cimeterre à deux mains ',
        prix: '75 po',
        degats: '2d4',
        critique: '18-20/x2',
        portee: '',
        poids: '4kg',
        special: '',
    },
    {
        id: '26',
        categorie: 'arme de corps à deux mains',
        nom: 'Corsèque',
        prix: '10 po',
        degats: '2d4',
        critique: '20/x3',
        portee: '',
        poids: '6kg',
        special: 'Allonge, Désarmement',
    },
    {
        id: '27',
        categorie: 'arme de corps à deux mains',
        nom: 'Coutille',
        prix: '8 po',
        degats: '1d10',
        critique: '20/x3',
        portee: '',
        poids: '5kg',
        special: 'Allonge',
    },
    {
        id: '28',
        categorie: 'arme de corps à deux mains',
        nom: 'Epée à deux mains',
        prix: '50 po',
        degats: '2d6',
        critique: '19-20/x2',
        portee: '',
        poids: '4kg',
        special: '',
    },
    {
        id: '29',
        categorie: 'arme de corps à deux mains',
        nom: 'Faux ',
        prix: '18 po',
        degats: '2d4',
        critique: '20/x4',
        portee: '',
        poids: '5kg',
        special: 'Croc-en-jambe',
    },
    {
        id: '30',
        categorie: 'arme de corps à deux mains',
        nom: 'Fléau d\'armes lourd',
        prix: '15 po',
        degats: '1d10',
        critique: '19-20/x2',
        portee: '',
        poids: '5kg',
        special: 'croc-en-jambe, Désarmement',
    },
    {
        id: '31',
        categorie: 'arme de corps à deux mains',
        nom: 'Glaive-guisarme',
        prix: '12 po',
        degats: '1d10',
        critique: '20/x3',
        portee: '',
        poids: '5kg',
        special: 'Allonge, Réception',
    },
    {
        id: '32',
        categorie: 'arme de corps à deux mains',
        nom: 'Grande hache',
        prix: '20 po',
        degats: '1d12',
        critique: '20/x3',
        portee: '',
        poids: '6kg',
        special: '',
    },
    {
        id: '33',
        categorie: 'arme de corps à deux mains',
        nom: 'Guisarme',
        prix: '9 po',
        degats: '2d4',
        critique: '20/x3',
        portee: '',
        poids: '6kg',
        special: 'Allonge, Croc-en-jambe',
    },
    {
        id: '34',
        categorie: 'arme de corps à deux mains',
        nom: 'Hallebarde',
        prix: '10 po',
        degats: '1d10',
        critique: '20/x3',
        portee: '',
        poids: '6kg',
        special: 'Croc-en-jambe, Réception',
    },
    {
        id: '35',
        categorie: 'arme de corps à deux mains',
        nom: 'Lance d\'arçon',
        prix: '10 po',
        degats: '1d8',
        critique: '20/x3',
        portee: '',
        poids: '5kg',
        special: 'Allonge',
    },
    {
        id: '36',
        categorie: 'arme de corps à deux mains',
        nom: 'Marteau de Lucerne',
        prix: '15 po',
        degats: '1d12',
        critique: '20/x2',
        portee: '',
        poids: '6kg',
        special: 'Allonge, Réception',
    },
    {
        id: '37',
        categorie: 'arme de corps à deux mains',
        nom: 'Massue',
        prix: '5 po',
        degats: '1d10',
        critique: '20/x2',
        portee: '',
        poids: '4kg',
        special: '',
    },
    {
        id: '38',
        categorie: 'arme de corps à deux mains',
        nom: 'Vouge',
        prix: '11 po',
        degats: '1d8',
        critique: '20/x3',
        portee: '',
        poids: '5,5kg',
        special: 'Allonge, Désarmement',
    },
    {
        id: '39',
        categorie: 'arme à distance',
        nom: 'Arc court',
        prix: '30 po',
        degats: '1d6',
        critique: '20/x3',
        portee: '18m',
        poids: '1kg',
        special: '',
    },
    {
        id: '40',
        categorie: 'arme à distance',
        nom: 'Arc court composite',
        prix: '75 po',
        degats: '1d6',
        critique: '20/x3',
        portee: '21m',
        poids: '1kg',
        special: '',
    },
    {
        id: '41',
        categorie: 'arme à distance',
        nom: 'Arc long',
        prix: '75 po',
        degats: '1d8',
        critique: '20/x3',
        portee: '30m',
        poids: '1,5kg',
        special: '',
    },
    {
        id: '42',
        categorie: 'arme à distance',
        nom: 'Arc long composite',
        prix: '100 po',
        degats: '1d8',
        critique: '20/x3',
        portee: '33m',
        poids: '1,5kg',
        special: '',
    },
    {
        id: '43',
        categorie: 'arme à distance',
        nom: 'Chakram',
        prix: '1 po',
        degats: '1d8',
        critique: '20/x2',
        portee: '9m',
        poids: '500g',
        special: '',
    },
    {
        id: '44',
        categorie: 'arme à distance',
        nom: 'Pilum',
        prix: '5 po',
        degats: '1d8',
        critique: '20/x2',
        portee: '9m',
        poids: '2,5kg',
        special: '',
    }
];
