import { Arme } from './arme';

export const ArmeCouranteCollection: Arme[] = [
    {
        id: '1',
        categorie: 'arme de corps à corps légère',
        nom: 'Ceste',
        prix: '5 po',
        degats: '1d4',
        critique: '19-20/x2',
        portee: '',
        poids: '500g',
        special: '',
    },
    {
        id: '2',
        categorie: 'arme de corps à corps légère',
        nom: 'Coup-de-Poing américain',
        prix: '1 po',
        degats: '1d3',
        critique: '20/x2',
        portee: '',
        poids: '500g',
        special: '',
    },
    {
        id: '3',
        categorie: 'arme de corps à corps légère',
        nom: 'Dague',
        prix: '2 po',
        degats: '1d4',
        critique: '19-20/x2',
        portee: '3m',
        poids: '500g',
        special: '',
    },
    {
        id: '4',
        categorie: 'arme de corps à corps légère',
        nom: 'Dague coup-de-poing',
        prix: '2 po',
        degats: '1d4',
        critique: '20/x3',
        portee: '',
        poids: '500g',
        special: '',
    },
    {
        id: '5',
        categorie: 'arme de corps à corps légère',
        nom: 'Ganttelet',
        prix: '2 po',
        degats: '1d3',
        critique: '20/x2',
        portee: '',
        poids: '500g',
        special: '',
    },
    {
        id: '6',
        categorie: 'arme de corps à corps légère',
        nom: 'Gantlet clouté',
        prix: '5 po',
        degats: '1d4',
        critique: '20/x2',
        portee: '',
        poids: '500g',
        special: '',
    },
    {
        id: '7',
        categorie: 'arme de corps à corps légère',
        nom: 'Goupillon de combat',
        prix: '5 po',
        degats: '1d6',
        critique: '20/x2',
        portee: '',
        poids: '2kg',
        special: '',
    },
    {
        id: '8',
        categorie: 'arme de corps à corps légère',
        nom: 'Masse d\'arme légère',
        prix: '5 po',
        degats: '1d6',
        critique: '20/x2',
        portee: '',
        poids: '2kg',
        special: '',
    },
    {
        id: '9',
        categorie: 'arme de corps à corps légère',
        nom: 'Pieu de bois',
        prix: '5 po',
        degats: '1d4',
        critique: '20/x2',
        portee: '3m',
        poids: '500g',
        special: '',
    },
    {
        id: '10',
        categorie: 'arme de corps à corps légère',
        nom: 'Serpe',
        prix: '6 po',
        degats: '1d6',
        critique: '20/x2',
        portee: '',
        poids: '1kg',
        special: 'Croc-en-jambe',
    },
    {
        id: '11',
        categorie: 'arme de corps à une main',
        nom: 'Epieu',
        prix: '1 po',
        degats: '1d6',
        critique: '20/x2',
        portee: '6m',
        poids: '1,5kg',
        special: '',
    },
    {
        id: '12',
        categorie: 'arme de corps à une main',
        nom: 'Gourdin',
        prix: '0 po',
        degats: '1d6',
        critique: '20/x2',
        portee: '',
        poids: '1,5kg',
        special: '',
    },
    {
        id: '13',
        categorie: 'arme de corps à une main',
        nom: 'Masse d\'armes lourde',
        prix: '12 po',
        degats: '1d8',
        critique: '20/x2',
        portee: '',
        poids: '4kg',
        special: '',
    },
    {
        id: '14',
        categorie: 'arme de corps à une main',
        nom: 'Morgenstern',
        prix: '8 po',
        degats: '1d8',
        critique: '20/x2',
        portee: '',
        poids: '3kg',
        special: '',
    },
    {
        id: '15',
        categorie: 'arme de corps à deux mains',
        nom: 'Baïonnette',
        prix: '5 po',
        degats: '1d6',
        critique: '20/x2',
        portee: '',
        poids: '2kg',
        special: '',
    },
    {
        id: '16',
        categorie: 'arme de corps à deux mains',
        nom: 'Bâton',
        prix: '0 po',
        degats: '1d6/1d6',
        critique: '20/x2',
        portee: '',
        poids: '2kg',
        special: '',
    },
    {
        id: '17',
        categorie: 'arme de corps à deux mains',
        nom: 'Lance',
        prix: '2 po',
        degats: '1d8',
        critique: '20/x3',
        portee: '6m',
        poids: '3kg',
        special: 'Réception',
    },
    {
        id: '18',
        categorie: 'arme de corps à deux mains',
        nom: 'Lance d\'arrêt',
        prix: '5 po',
        degats: '1d8',
        critique: '20/x2',
        portee: '',
        poids: '4kg',
        special: 'Réception',
    },
    {
        id: '19',
        categorie: 'arme de corps à deux mains',
        nom: 'Pique',
        prix: '5 po',
        degats: '1d8',
        critique: '20/x3',
        portee: '',
        poids: '4,5kg',
        special: 'Allongé, Réception',
    },
    {
        id: '20',
        categorie: 'arme à distance',
        nom: 'Arbalète légère',
        prix: '35 po',
        degats: '1d8',
        critique: '19-20/x2',
        portee: '24m',
        poids: '2kg',
        special: '',
    },
    {
        id: '21',
        categorie: 'arme à distance',
        nom: 'Arbalète lourde',
        prix: '50 po',
        degats: '1d10',
        critique: '19-20/x2',
        portee: '36m',
        poids: '4kg',
        special: '',
    },
    {
        id: '22',
        categorie: 'arme à distance',
        nom: 'Fléchette',
        prix: '5 pa',
        degats: '1d4',
        critique: '20/x2',
        portee: '6m',
        poids: '250g',
        special: '',
    },
    {
        id: '23',
        categorie: 'arme à distance',
        nom: 'Fronde',
        prix: '0 po',
        degats: '1d4',
        critique: '20/x2',
        portee: '15m',
        poids: '0 kg',
        special: '',
    },
    {
        id: '24',
        categorie: 'arme à distance',
        nom: 'Javeline',
        prix: '1 po',
        degats: '1d6',
        critique: '20/x2',
        portee: '9m',
        poids: '500g',
        special: '',
    }
    ];
