import { CourbesJs } from './courbes-js';

export const courbesJsData: CourbesJs[] = [
    { id: 1, type: 'Sauvegarde', courbe: 'Faible', niveau: 1, valeur: 0 },
    { id: 2, type: 'Sauvegarde', courbe: 'Faible', niveau: 2, valeur: 0 },
    { id: 3, type: 'Sauvegarde', courbe: 'Faible', niveau: 3, valeur: 1 },
    { id: 4, type: 'Sauvegarde', courbe: 'Faible', niveau: 4, valeur: 1 },
    { id: 5, type: 'Sauvegarde', courbe: 'Faible', niveau: 5, valeur: 1 },
    { id: 6, type: 'Sauvegarde', courbe: 'Faible', niveau: 6, valeur: 2 },
    { id: 7, type: 'Sauvegarde', courbe: 'Faible', niveau: 7, valeur: 2 },
    { id: 8, type: 'Sauvegarde', courbe: 'Faible', niveau: 8, valeur: 2 },
    { id: 9, type: 'Sauvegarde', courbe: 'Faible', niveau: 9, valeur: 3 },
    { id: 10, type: 'Sauvegarde', courbe: 'Faible', niveau: 10, valeur: 3 },
    { id: 11, type: 'Sauvegarde', courbe: 'Faible', niveau: 11, valeur: 3 },
    { id: 12, type: 'Sauvegarde', courbe: 'Faible', niveau: 12, valeur: 4 },
    { id: 13, type: 'Sauvegarde', courbe: 'Faible', niveau: 13, valeur: 4 },
    { id: 14, type: 'Sauvegarde', courbe: 'Faible', niveau: 14, valeur: 4 },
    { id: 15, type: 'Sauvegarde', courbe: 'Faible', niveau: 15, valeur: 5 },
    { id: 16, type: 'Sauvegarde', courbe: 'Faible', niveau: 16, valeur: 5 },
    { id: 17, type: 'Sauvegarde', courbe: 'Faible', niveau: 17, valeur: 5 },
    { id: 18, type: 'Sauvegarde', courbe: 'Faible', niveau: 18, valeur: 6 },
    { id: 19, type: 'Sauvegarde', courbe: 'Faible', niveau: 19, valeur: 6 },
    { id: 20, type: 'Sauvegarde', courbe: 'Faible', niveau: 20, valeur: 6 },
    { id: 21, type: 'Sauvegarde', courbe: 'Haute', niveau: 1, valeur: 2 },
    { id: 22, type: 'Sauvegarde', courbe: 'Haute', niveau: 2, valeur: 3 },
    { id: 23, type: 'Sauvegarde', courbe: 'Haute', niveau: 3, valeur: 3 },
    { id: 24, type: 'Sauvegarde', courbe: 'Haute', niveau: 4, valeur: 4 },
    { id: 25, type: 'Sauvegarde', courbe: 'Haute', niveau: 5, valeur: 4 },
    { id: 26, type: 'Sauvegarde', courbe: 'Haute', niveau: 6, valeur: 5 },
    { id: 27, type: 'Sauvegarde', courbe: 'Haute', niveau: 7, valeur: 5 },
    { id: 28, type: 'Sauvegarde', courbe: 'Haute', niveau: 8, valeur: 6 },
    { id: 29, type: 'Sauvegarde', courbe: 'Haute', niveau: 9, valeur: 6 },
    { id: 30, type: 'Sauvegarde', courbe: 'Haute', niveau: 10, valeur: 7 },
    { id: 31, type: 'Sauvegarde', courbe: 'Haute', niveau: 11, valeur: 7 },
    { id: 32, type: 'Sauvegarde', courbe: 'Haute', niveau: 12, valeur: 8 },
    { id: 33, type: 'Sauvegarde', courbe: 'Haute', niveau: 13, valeur: 8 },
    { id: 34, type: 'Sauvegarde', courbe: 'Haute', niveau: 14, valeur: 9 },
    { id: 35, type: 'Sauvegarde', courbe: 'Haute', niveau: 15, valeur: 9 },
    { id: 36, type: 'Sauvegarde', courbe: 'Haute', niveau: 16, valeur: 10 },
    { id: 37, type: 'Sauvegarde', courbe: 'Haute', niveau: 17, valeur: 10 },
    { id: 38, type: 'Sauvegarde', courbe: 'Haute', niveau: 18, valeur: 11 },
    { id: 39, type: 'Sauvegarde', courbe: 'Haute', niveau: 19, valeur: 11 },
    { id: 40, type: 'Sauvegarde', courbe: 'Haute', niveau: 20, valeur: 12 }
];
